version: '3.8'

services:
  db:
    image: postgres:15
    container_name: comparasalud-db
    restart: always
    environment:
      POSTGRES_DB: db_ComparaSalud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: comparasalud-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_ComparaSalud
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: comparasalud-super-secret-key-minimum-256-bits-long-for-hs256-algorithm
      JWT_EXPIRATION_MS: 86400000
      APP_BASE_URL: http://localhost:8081
      IP_FRONTEND: http://localhost:4200

volumes:
  postgres_data: