spring.application.name=ComparaSalud
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/db_ComparaSalud
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ip.frontend=http://54.145.56.133:4200

jwt.secret=comparasalud-super-secret-key-minimum-256-bits-long-for-hs256-algorithm
jwt.expiration-ms=86400000

# App
app.base-url=http://localhost:8081
app.upload-dir=uploads/photos

# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true